name: main

env:
  WERF_VERSION: "1.1 ea"
  UPSTREAM_REPO: "flant/helm-charts"

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

_snippet: &install_dependencies
  name: Install dependencies
  run: |
    sudo apt-get -qq update
    sudo apt-get -qq install python3 python3-setuptools
    sudo pip3 install yq doit

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - <<: *install_dependencies
      - name: Setup multiwerf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Werf lint charts
        run: 'doit werf-lint -v "$WERF_VERSION"'
      - name: Werf render charts
        run: 'doit werf-render -v "$WERF_VERSION"'
      - name: Package werf charts
        run: 'doit werf-package-charts'
        if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == env.UPSTREAM_REPO"
      - name: Publish packaged werf charts
        run: 'doit werf-publish-chart-packages'
        if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == env.UPSTREAM_REPO"
