name: main

env:
  WERF_VERSION: "1.1 ea"
  UPSTREAM_REPO: "flant/helm-charts"

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "./.github/actions/install-dependencies"
      - uses: "./.github/actions/setup-multiwerf"
      - name: Werf lint charts
        run: 'doit werf-lint -v "$WERF_VERSION"'
      - name: Werf render charts
        run: 'doit werf-render -v "$WERF_VERSION"'
      - name: Package werf charts
        run: 'doit werf-package-charts'
        if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == env.UPSTREAM_REPO"
      - name: Publish packaged werf charts
        run: 'doit werf-publish-chart-packages'
        if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == env.UPSTREAM_REPO"
