name: tests

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  WERF_VERSION: 1.1 ea

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install make python
          sudo pip install yq
      - name: Install multiwerf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
      - name: Lint charts
        run: |
          source <(~/bin/multiwerf use $WERF_VERSION)
          while read chart; do
            CHART="$chart" make lint
          done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d)
      - name: Test charts
        run: |
          source <(~/bin/multiwerf use $WERF_VERSION)
          while read chart; do
            CHART="$chart" make test
          done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d)
