name: tests

env:
  WERF_VERSION: "1.1 ea"
  HELM_VERSION: "3.4.1"

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install python3 python3-setuptools
          sudo pip3 install yq doit
          curl -sSLO https://get.helm.sh/helm-v{HELM_VERSION}-linux-amd64.tar.gz
          tar xf helm-v{HELM_VERSION}-linux-amd64.tar.gz
          install -t /usr/local/bin/ linux-amd64/helm
      - name: Setup multiwerf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Lint charts
        run: "doit lint --werf-version {WERF_VERSION}"
      - name: Render charts
        run: "doit render --werf-version {WERF_VERSION}"
