name: tests

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  WERF_VERSION: "1.1 ea"
  TERM: "xterm"

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - name: Install system dependencies
        run: |
          sudo apt-get -qq update
          # FIXME:
          sudo apt-get -qq install make python strace
          sudo pip install yq
      - name: Setup werf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
        shell: "echo exit > out; echo {0}"
      - name: Lint charts
        run: |
          cat out
          env
          export PATH="$PATH:$HOME/bin"
          while read chart; do
            CHART="$chart" make lint
          done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d -exec basename '{}' \;)
      - name: Test charts
        run: |
          export PATH="$PATH:$HOME/bin"
          while read chart; do
            CHART="$chart" make test
          done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d -exec basename '{}' \;)
