name: tests

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

env:
  WERF_VERSION: "1.1 ea"
  TERM: "xterm"

jobs:
  tests:
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - name: Install system dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install make python
          sudo pip install yq
      - name: Setup werf
        run: |
          mkdir -p ~/bin
          cd ~/bin
          curl -sSL https://raw.githubusercontent.com/werf/multiwerf/master/get.sh | bash
          which bash
          id
          echo 'touch /home/runner/test1' >> /home/runneradmin/.bash_profile
          echo 'touch /home/runner/test2' >> /home/runneradmin/.bashrc
          echo 'touch /home/runner/test3' >> /home/runneradmin/.profile
          echo 'touch /home/runner/test4' >> /home/runner/.bash_profile
          echo 'touch /home/runner/test5' >> /home/runner/.bashrc
          echo 'touch /home/runner/test6' >> /home/runner/.profile
          echo 'touch /home/runner/test7' >> /etc/bash.bashrc
          echo 'touch /home/runner/test8' >> /etc/skel/.bashrc
          echo 'touch /home/runner/test9' >> /etc/environment
          echo 'touch /home/runner/test10' >> /etc/profile.d/apps-bin-path.sh
        shell: "bash -l {0}"
      - name: Lint charts
        run: |
          export PATH="$PATH:$HOME/bin"
          while read chart; do
            CHART="$chart" make lint
          done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d -exec basename '{}' \;)
        shell: "bash -l {0}"
      # - name: Test charts
      #   run: |
      #     export PATH="$PATH:$HOME/bin"
      #     while read chart; do
      #       CHART="$chart" make test
      #     done < <(find .helm/charts -mindepth 1 -maxdepth 1 -type d -exec basename '{}' \;)
